name: Build Metadata Index

on:
  push:
    paths:
      - "output/metadata/*.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build index.json
        run: |
          python << 'EOF'
          import os, json

          METADATA_DIR = "output/metadata"
          INDEX_FILE = os.path.join(METADATA_DIR, "index.json")
          ALL_POSTS_FILE = os.path.join(METADATA_DIR, "all_posts.json")

          files = sorted(
              f for f in os.listdir(METADATA_DIR)
              if f.startswith("posts_") and f.endswith(".json")
          )

          if not files:
              raise RuntimeError("No post files found")

          all_posts = []
          for f in files:
              with open(os.path.join(METADATA_DIR, f), "r", encoding="utf-8") as fh:
                  data = json.load(fh)
                  if isinstance(data, list):
                      all_posts.extend(data)

          all_posts.sort(key=lambda p: p.get("date",""), reverse=True)

          with open(INDEX_FILE, "w", encoding="utf-8") as f:
              json.dump(files, f, indent=2)

          with open(ALL_POSTS_FILE, "w", encoding="utf-8") as f:
              json.dump(all_posts, f, indent=2)

          print("✅ index.json + all_posts.json rebuilt")
          EOF

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/metadata/index.json output/metadata/all_posts.json
          git commit -m "Auto rebuild index" || echo "No changes"
          git push
